version: '3'
services:
  #Administration Api
  promocode-factory-administration-api:
    build: src/Otus.Teaching.Pcf.Administration/
    container_name: 'promocode-factory-administration-api'
    restart: always
    ports:
      - "8091:80"       
    depends_on: 
      - promocode-factory-administration-db
  #Administration Db
  promocode-factory-administration-db:
    image: "mongo:4.2.3"
    container_name: 'promocode-factory-administration-db'
    restart: always 
    ports:
      - 27017:27017
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password